/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turnero;

import bean.DBconnection;
import bean.id_login;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.math.MathContext;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.charts.JRXAxisFormat;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author janer
 */
public class Administrador extends javax.swing.JFrame implements Runnable {

    String hora, minuto, segundo;
    Thread hilo;
    Connection connection;
    String url = "jdbc:postgresql://localhost:5432/Turnero";
    String user = "postgres";
    String password = "123";

    /**
     * Creates new form Main
     */
    public Administrador() {
        initComponents();
        setLocationRelativeTo(null);
        lblfecha.setText(" " + fecha());
        hilo = new Thread(this);
        hilo.start();

    }

    public void hora() {
        Calendar calendario = new GregorianCalendar();
        Date horactual = new Date();
        calendario.setTime(horactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minuto = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundo = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    public void run() {
        Thread current = Thread.currentThread();
        while (current == hilo) {
            hora();
            lblhora.setText(" " + hora + ":" + minuto + ":" + segundo);
        }
    }

    public static String fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rsnpanel = new rojeru_san.RSPanelsSlider();
        pnlCrearCaja = new javax.swing.JPanel();
        lbltituloconf2 = new RSMaterialComponent.RSLabelTextIcon();
        btnNewCaja = new rojerusan.RSButtonIconI();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new rojeru_san.RSMTextFull();
        txtapellido = new rojeru_san.RSMTextFull();
        txtcaja = new rojeru_san.RSMTextFull();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtuser = new rojeru_san.RSMTextFull();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtpass = new rojeru_san.RSMPassView();
        txtpass2 = new rojeru_san.RSMPassView();
        pnlReporte = new javax.swing.JPanel();
        lbltituloconf1 = new RSMaterialComponent.RSLabelTextIcon();
        btnReport = new rojerusan.RSButtonIconI();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        combocaja = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        pnlcajareporte = new javax.swing.JPanel();
        pnlconfiguracion = new javax.swing.JPanel();
        lbltituloconf = new RSMaterialComponent.RSLabelTextIcon();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtconfig_user = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnewpass = new rojeru_san.RSMPassView();
        jLabel4 = new javax.swing.JLabel();
        txtnewpass2 = new rojeru_san.RSMPassView();
        btnupdate = new rojerusan.RSButtonIconI();
        pnlsoporte = new javax.swing.JPanel();
        lbltitulosoporte = new RSMaterialComponent.RSLabelTextIcon();
        jPanel4 = new javax.swing.JPanel();
        lbltitulosoporte4 = new RSMaterialComponent.RSLabelTextIcon();
        lbltitulosoporte2 = new RSMaterialComponent.RSLabelTextIcon();
        jPanel5 = new javax.swing.JPanel();
        lbltitulosoporte3 = new RSMaterialComponent.RSLabelTextIcon();
        lbltitulosoporte1 = new RSMaterialComponent.RSLabelTextIcon();
        jPanel6 = new javax.swing.JPanel();
        lbltitulosoporte5 = new RSMaterialComponent.RSLabelTextIcon();
        lbltitulosoporte6 = new RSMaterialComponent.RSLabelTextIcon();
        lblfecha = new RSMaterialComponent.RSLabelTextIcon();
        lblhora = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        rSButtonIconI6 = new rojerusan.RSButtonIconI();
        btnCrearCaja = new rojerusan.RSButtonIconI();
        btnReporte = new rojerusan.RSButtonIconI();
        btnConfig = new rojerusan.RSButtonIconI();
        btnSoporte = new rojerusan.RSButtonIconI();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Administrador - Sistema Control de Turnos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel8)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        pnlCrearCaja.setBackground(new java.awt.Color(255, 255, 255));
        pnlCrearCaja.setName("pnlCrearCaja"); // NOI18N

        lbltituloconf2.setForeground(new java.awt.Color(0, 0, 0));
        lbltituloconf2.setText("Crear Caja");
        lbltituloconf2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lbltituloconf2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);

        btnNewCaja.setBackground(new java.awt.Color(0, 153, 0));
        btnNewCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/New_Caja.png"))); // NOI18N
        btnNewCaja.setText("Guardar");
        btnNewCaja.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnNewCaja.setInheritsPopupMenu(true);
        btnNewCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCajaActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        txtnombre.setPlaceholder("");
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtapellido.setPlaceholder("");
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });

        txtcaja.setPlaceholder("");
        txtcaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcajaKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("Numero de Caja:");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setText("Datos Personales");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(txtcaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel10)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Credenciales");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("Usuario:");

        txtuser.setPlaceholder("");
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuserKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel13.setText("Contraseña:");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel14.setText("Repetir Contraseña:");

        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassKeyTyped(evt);
            }
        });

        txtpass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpass2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel11))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtpass2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCrearCajaLayout = new javax.swing.GroupLayout(pnlCrearCaja);
        pnlCrearCaja.setLayout(pnlCrearCajaLayout);
        pnlCrearCajaLayout.setHorizontalGroup(
            pnlCrearCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearCajaLayout.createSequentialGroup()
                .addGroup(pnlCrearCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCrearCajaLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbltituloconf2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCrearCajaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlCrearCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCrearCajaLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnNewCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlCrearCajaLayout.setVerticalGroup(
            pnlCrearCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearCajaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbltituloconf2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnNewCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        rsnpanel.add(pnlCrearCaja, "card3");

        pnlReporte.setBackground(new java.awt.Color(255, 255, 255));
        pnlReporte.setName("pnlReporte"); // NOI18N

        lbltituloconf1.setForeground(new java.awt.Color(0, 0, 0));
        lbltituloconf1.setText("Reporte");
        lbltituloconf1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lbltituloconf1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BOOK);

        btnReport.setBackground(new java.awt.Color(0, 153, 0));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/generar_report.png"))); // NOI18N
        btnReport.setText("Generar");
        btnReport.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnReport.setInheritsPopupMenu(true);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jCheckBox1.setText("View All");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("Fecha:");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel15.setText("Caja");

        combocaja.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        pnlcajareporte.setBackground(new java.awt.Color(255, 255, 255));
        pnlcajareporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlcajareporteLayout = new javax.swing.GroupLayout(pnlcajareporte);
        pnlcajareporte.setLayout(pnlcajareporteLayout);
        pnlcajareporteLayout.setHorizontalGroup(
            pnlcajareporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlcajareporteLayout.setVerticalGroup(
            pnlcajareporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlReporteLayout = new javax.swing.GroupLayout(pnlReporte);
        pnlReporte.setLayout(pnlReporteLayout);
        pnlReporteLayout.setHorizontalGroup(
            pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlcajareporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlReporteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlReporteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbltituloconf1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteLayout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combocaja, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlReporteLayout.setVerticalGroup(
            pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltituloconf1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(combocaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlcajareporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        rsnpanel.add(pnlReporte, "card4");

        pnlconfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        pnlconfiguracion.setName("pnlconfiguracion"); // NOI18N

        lbltituloconf.setForeground(new java.awt.Color(0, 0, 0));
        lbltituloconf.setText("Configuracion");
        lbltituloconf.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lbltituloconf.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");

        txtconfig_user.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtconfig_user.setText("tu usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtconfig_user, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtconfig_user)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Nueva Contraseña");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Repetir Contraseña");

        btnupdate.setBackground(new java.awt.Color(0, 153, 0));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/actualizar.png"))); // NOI18N
        btnupdate.setText("Actualizar");
        btnupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnupdate.setInheritsPopupMenu(true);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlconfiguracionLayout = new javax.swing.GroupLayout(pnlconfiguracion);
        pnlconfiguracion.setLayout(pnlconfiguracionLayout);
        pnlconfiguracionLayout.setHorizontalGroup(
            pnlconfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlconfiguracionLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(pnlconfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlconfiguracionLayout.createSequentialGroup()
                        .addGroup(pnlconfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(pnlconfiguracionLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlconfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtnewpass2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                                .addComponent(txtnewpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlconfiguracionLayout.createSequentialGroup()
                        .addComponent(lbltituloconf, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        pnlconfiguracionLayout.setVerticalGroup(
            pnlconfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlconfiguracionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbltituloconf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnewpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        rsnpanel.add(pnlconfiguracion, "card5");

        pnlsoporte.setBackground(new java.awt.Color(255, 255, 255));
        pnlsoporte.setName("pnlsoporte"); // NOI18N

        lbltitulosoporte.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte.setText("Soporte Tecnico");
        lbltitulosoporte.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lbltitulosoporte.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WIFI_TETHERING);

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));

        lbltitulosoporte4.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte4.setText(" +593 99 757 3608");
        lbltitulosoporte4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbltitulosoporte4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);

        lbltitulosoporte2.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte2.setText(" Victor Romero");
        lbltitulosoporte2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbltitulosoporte2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulosoporte2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(lbltitulosoporte4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulosoporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulosoporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));

        lbltitulosoporte3.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte3.setText(" Janer Torrales");
        lbltitulosoporte3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbltitulosoporte3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);

        lbltitulosoporte1.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte1.setText(" +593 99 330 3546");
        lbltitulosoporte1.setToolTipText("");
        lbltitulosoporte1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbltitulosoporte1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulosoporte3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(lbltitulosoporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulosoporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulosoporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 153));

        lbltitulosoporte5.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte5.setText(" Wladimir Tocta");
        lbltitulosoporte5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbltitulosoporte5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);

        lbltitulosoporte6.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte6.setText(" +593 99 725 1924");
        lbltitulosoporte6.setToolTipText("");
        lbltitulosoporte6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbltitulosoporte6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulosoporte5, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(lbltitulosoporte6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulosoporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulosoporte6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlsoporteLayout = new javax.swing.GroupLayout(pnlsoporte);
        pnlsoporte.setLayout(pnlsoporteLayout);
        pnlsoporteLayout.setHorizontalGroup(
            pnlsoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsoporteLayout.createSequentialGroup()
                .addGroup(pnlsoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlsoporteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbltitulosoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlsoporteLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pnlsoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        pnlsoporteLayout.setVerticalGroup(
            pnlsoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsoporteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbltitulosoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        rsnpanel.add(pnlsoporte, "card2");

        jPanel1.add(rsnpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 35, 670, 660));

        lblfecha.setForeground(new java.awt.Color(0, 0, 0));
        lblfecha.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        lblfecha.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        lblfecha.setName("lblfecha"); // NOI18N
        jPanel1.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 23));

        lblhora.setForeground(new java.awt.Color(0, 0, 0));
        lblhora.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        lblhora.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        lblhora.setName("lblhora"); // NOI18N
        jPanel1.add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 189, 24));

        rSLabelImage1.setBackground(new java.awt.Color(255, 255, 255));
        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 138));

        rSButtonIconI6.setBackground(new java.awt.Color(0, 153, 0));
        rSButtonIconI6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cerrar.png"))); // NOI18N
        rSButtonIconI6.setText("Cerrar Sesion");
        rSButtonIconI6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        rSButtonIconI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconI6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        btnCrearCaja.setBackground(new java.awt.Color(0, 153, 0));
        btnCrearCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/crear_caja.png"))); // NOI18N
        btnCrearCaja.setText("Crear Caja");
        btnCrearCaja.setFont(new java.awt.Font("Comic Sans MS", 1, 17)); // NOI18N
        btnCrearCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnReporte.setBackground(new java.awt.Color(0, 153, 0));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        btnReporte.setText("Reporte");
        btnReporte.setFont(new java.awt.Font("Comic Sans MS", 1, 17)); // NOI18N
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        btnConfig.setBackground(new java.awt.Color(0, 153, 0));
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/configuracion.png"))); // NOI18N
        btnConfig.setText("Configuracion");
        btnConfig.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        btnSoporte.setBackground(new java.awt.Color(0, 153, 0));
        btnSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/soporte.png"))); // NOI18N
        btnSoporte.setText("Soporte Tecnico");
        btnSoporte.setFont(new java.awt.Font("Comic Sans MS", 1, 17)); // NOI18N
        btnSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 255, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/17046-4k.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI6ActionPerformed
        Login abrir = new Login();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonIconI6ActionPerformed

    private void btnCrearCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCajaActionPerformed
        if (!this.btnCrearCaja.isSelected()) {
            this.btnCrearCaja.setSelected(true);
            this.btnConfig.setSelected(false);
            this.btnReporte.setSelected(false);
            this.btnSoporte.setSelected(false);

            this.rsnpanel.setPanelSlider(2, pnlCrearCaja, rojeru_san.RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnCrearCajaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        if (!this.btnReporte.isSelected()) {
            //seleccionar boton
            this.btnCrearCaja.setSelected(false);
            this.btnConfig.setSelected(false);
            this.btnReporte.setSelected(true);
            this.btnSoporte.setSelected(false);
            //mostrar panel seleccionado
            this.rsnpanel.setPanelSlider(2, pnlReporte, rojeru_san.RSPanelsSlider.DIRECT.RIGHT);
            //llenar combo con las cajeras
            DBconnection conex = new DBconnection();
            Map<Integer, String> map = new HashMap<>();
            map = conex.combocajera();
            combocaja.addItem("");
            for (Map.Entry<Integer, String> entry : map.entrySet()) {
                Integer key = entry.getKey();
                combocaja.addItem(entry.getValue());
            }
            connec();
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        if (!this.btnConfig.isSelected()) {
            this.btnCrearCaja.setSelected(false);
            this.btnConfig.setSelected(true);
            this.btnReporte.setSelected(false);
            this.btnSoporte.setSelected(false);

            this.rsnpanel.setPanelSlider(2, pnlconfiguracion, rojeru_san.RSPanelsSlider.DIRECT.RIGHT);
            id_login datos = new id_login();
            txtconfig_user.setText(datos.getUsuario());
        }
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoporteActionPerformed
        if (!this.btnSoporte.isSelected()) {
            this.btnCrearCaja.setSelected(false);
            this.btnConfig.setSelected(false);
            this.btnReporte.setSelected(false);
            this.btnSoporte.setSelected(true);

            this.rsnpanel.setPanelSlider(2, pnlsoporte, rojeru_san.RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnSoporteActionPerformed

    private void btnNewCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCajaActionPerformed

        if (txtpass.getText().equals(txtpass2.getText())) {
            DBconnection conex = new DBconnection();
            boolean resultado = conex.CrearCaja(txtuser.getText(), txtpass.getText(),
                    txtnombre.getText(), txtapellido.getText(), Integer.parseInt(txtcaja.getText()));
            if (resultado == true) {
                JOptionPane.showMessageDialog(null, "ingreso exitoso");
                txtnombre.setText("");
                txtapellido.setText("");
                txtcaja.setText("");
                txtuser.setText("");
                txtpass.setText("");
                txtpass2.setText("");

            } else {
                JOptionPane.showMessageDialog(null, "error ingreso");
            }

        } else {
            JOptionPane.showMessageDialog(null, "las contraseñas no coinciden");
        }
    }//GEN-LAST:event_btnNewCajaActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyTyped

    }//GEN-LAST:event_txtpassKeyTyped

    private void txtpass2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpass2KeyTyped

    }//GEN-LAST:event_txtpass2KeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtuserKeyTyped

    private void txtcajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcajaKeyTyped
        char car = evt.getKeyChar();
        if (Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtcajaKeyTyped

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        if (txtnewpass.getText().equals(txtnewpass2.getText())) {
            DBconnection conex = new DBconnection();
            boolean resultado = conex.actualizarclave(txtnewpass.getText());
            if (resultado == true) {
                JOptionPane.showMessageDialog(null, "contraseña actualizada correctamente");
                txtnewpass.setText("");
                txtnewpass2.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "error en actulizacion de contraseña");
            }
        } else {
            JOptionPane.showMessageDialog(null, "las contraseñas no coinciden");
        }
    }//GEN-LAST:event_btnupdateActionPerformed
    PreparedStatement pst;

    public void connec() {
        try {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection(url, user, password);
        } catch (ClassNotFoundException | SQLException e) {
        }
    }
    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if (jCheckBox1.isSelected()) {
            try {

                HashMap a = new HashMap();
                pnlcajareporte.removeAll();
                pnlcajareporte.repaint();
                pnlcajareporte.revalidate();
                JasperDesign jdesing = JRXmlLoader.load("C:\\Users\\janer\\Documents\\Trabajo\\Turnero\\aplicacion\\src\\reportes\\reportecaja.jrxml");
                JasperReport jreport = JasperCompileManager.compileReport(jdesing);
                JasperPrint jprint = JasperFillManager.fillReport(jreport, a, connection);
                JRViewer v = new JRViewer(jprint);
                pnlcajareporte.setLayout(new BorderLayout());
                
                pnlcajareporte.add(v);

            } catch (Exception e) {
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI btnConfig;
    private rojerusan.RSButtonIconI btnCrearCaja;
    private rojerusan.RSButtonIconI btnNewCaja;
    private rojerusan.RSButtonIconI btnReport;
    private rojerusan.RSButtonIconI btnReporte;
    private rojerusan.RSButtonIconI btnSoporte;
    private rojerusan.RSButtonIconI btnupdate;
    private javax.swing.JComboBox<String> combocaja;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private RSMaterialComponent.RSLabelTextIcon lblfecha;
    private RSMaterialComponent.RSLabelTextIcon lblhora;
    private RSMaterialComponent.RSLabelTextIcon lbltituloconf;
    private RSMaterialComponent.RSLabelTextIcon lbltituloconf1;
    private RSMaterialComponent.RSLabelTextIcon lbltituloconf2;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte1;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte2;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte3;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte4;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte5;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte6;
    private javax.swing.JPanel pnlCrearCaja;
    private javax.swing.JPanel pnlReporte;
    private javax.swing.JPanel pnlcajareporte;
    private javax.swing.JPanel pnlconfiguracion;
    private javax.swing.JPanel pnlsoporte;
    private rojerusan.RSButtonIconI rSButtonIconI6;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojeru_san.RSPanelsSlider rsnpanel;
    private rojeru_san.RSMTextFull txtapellido;
    private rojeru_san.RSMTextFull txtcaja;
    private javax.swing.JLabel txtconfig_user;
    private rojeru_san.RSMPassView txtnewpass;
    private rojeru_san.RSMPassView txtnewpass2;
    private rojeru_san.RSMTextFull txtnombre;
    private rojeru_san.RSMPassView txtpass;
    private rojeru_san.RSMPassView txtpass2;
    private rojeru_san.RSMTextFull txtuser;
    // End of variables declaration//GEN-END:variables

}
