/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turnero;

import bean.DBconnection;
import bean.id_caja;
import bean.id_login;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author janer
 */
public class Menu extends javax.swing.JFrame implements Runnable {

    String hora, minuto, segundo;
    Thread hilo;

    /**
     * Creates new form Main
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        lblfecha.setText(" " + fecha());
        hilo = new Thread(this);
        hilo.start();

    }

    public void hora() {
        Calendar calendario = new GregorianCalendar();
        Date horactual = new Date();
        calendario.setTime(horactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minuto = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundo = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    public void run() {
        Thread current = Thread.currentThread();
        while (current == hilo) {
            hora();
            lblhora.setText(" " + hora + ":" + minuto + ":" + segundo);
        }
    }

    public static String fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rsnpanel = new rojeru_san.RSPanelsSlider();
        pnlTurno = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSButtonIconI1 = new rojerusan.RSButtonIconI();
        txtnumeroturno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JLabel();
        rSButtonIconI2 = new rojerusan.RSButtonIconI();
        pnlconfig = new javax.swing.JPanel();
        lbltituloconf = new RSMaterialComponent.RSLabelTextIcon();
        btnupdate = new rojerusan.RSButtonIconI();
        txtnewpass2 = new rojeru_san.RSMPassView();
        txtnewpass = new rojeru_san.RSMPassView();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtconfig_user = new javax.swing.JLabel();
        pnlsoporte = new javax.swing.JPanel();
        lbltitulosoporte = new RSMaterialComponent.RSLabelTextIcon();
        jPanel4 = new javax.swing.JPanel();
        lbltitulosoporte4 = new RSMaterialComponent.RSLabelTextIcon();
        lbltitulosoporte2 = new RSMaterialComponent.RSLabelTextIcon();
        jPanel6 = new javax.swing.JPanel();
        lbltitulosoporte5 = new RSMaterialComponent.RSLabelTextIcon();
        lbltitulosoporte6 = new RSMaterialComponent.RSLabelTextIcon();
        jPanel5 = new javax.swing.JPanel();
        lbltitulosoporte3 = new RSMaterialComponent.RSLabelTextIcon();
        lbltitulosoporte1 = new RSMaterialComponent.RSLabelTextIcon();
        lblfecha = new RSMaterialComponent.RSLabelTextIcon();
        lblhora = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        btnTurnos = new rojerusan.RSButtonIconI();
        btnConfig = new rojerusan.RSButtonIconI();
        btnSoporte = new rojerusan.RSButtonIconI();
        rSButtonIconI6 = new rojerusan.RSButtonIconI();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTurno.setBackground(new java.awt.Color(255, 255, 255));
        pnlTurno.setName("pnlTurno"); // NOI18N

        rSLabelTextIcon1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon1.setText("Turno");
        rSLabelTextIcon1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADJUST);

        rSButtonIconI1.setBackground(new java.awt.Color(0, 153, 0));
        rSButtonIconI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        rSButtonIconI1.setText("Siguiente Turno");
        rSButtonIconI1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        rSButtonIconI1.setInheritsPopupMenu(true);
        rSButtonIconI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI1ActionPerformed(evt);
            }
        });

        txtnumeroturno.setBackground(new java.awt.Color(255, 255, 255));
        txtnumeroturno.setFont(new java.awt.Font("Comic Sans MS", 1, 220)); // NOI18N
        txtnumeroturno.setForeground(new java.awt.Color(0, 153, 0));
        txtnumeroturno.setText("A000");
        txtnumeroturno.setToolTipText("");
        txtnumeroturno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("C. Cliente");

        txtcedula.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtcedula.setText("Cedula del cliente");

        rSButtonIconI2.setBackground(new java.awt.Color(0, 153, 0));
        rSButtonIconI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/discapacidad.png"))); // NOI18N
        rSButtonIconI2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        rSButtonIconI2.setInheritsPopupMenu(true);
        rSButtonIconI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTurnoLayout = new javax.swing.GroupLayout(pnlTurno);
        pnlTurno.setLayout(pnlTurnoLayout);
        pnlTurnoLayout.setHorizontalGroup(
            pnlTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTurnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addGroup(pnlTurnoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTurnoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(pnlTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTurnoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rSButtonIconI1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(rSButtonIconI2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(pnlTurnoLayout.createSequentialGroup()
                                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 109, Short.MAX_VALUE))))
                    .addGroup(pnlTurnoLayout.createSequentialGroup()
                        .addComponent(txtnumeroturno, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        pnlTurnoLayout.setVerticalGroup(
            pnlTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTurnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTurnoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumeroturno, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtcedula))
                        .addGap(105, 105, 105)
                        .addComponent(rSButtonIconI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTurnoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonIconI2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
        );

        rsnpanel.add(pnlTurno, "card3");

        pnlconfig.setBackground(new java.awt.Color(255, 255, 255));
        pnlconfig.setName("pnlconfig"); // NOI18N

        lbltituloconf.setForeground(new java.awt.Color(0, 0, 0));
        lbltituloconf.setText("Configuracion");
        lbltituloconf.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lbltituloconf.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);

        btnupdate.setBackground(new java.awt.Color(0, 153, 0));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/actualizar.png"))); // NOI18N
        btnupdate.setText("Actualizar");
        btnupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnupdate.setInheritsPopupMenu(true);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Repetir Contraseña");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Nueva Contraseña");

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");

        txtconfig_user.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtconfig_user.setText("tu usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtconfig_user, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtconfig_user)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlconfigLayout = new javax.swing.GroupLayout(pnlconfig);
        pnlconfig.setLayout(pnlconfigLayout);
        pnlconfigLayout.setHorizontalGroup(
            pnlconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlconfigLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltituloconf, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(pnlconfigLayout.createSequentialGroup()
                .addGroup(pnlconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlconfigLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnlconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(pnlconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnewpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(txtnewpass2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlconfigLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlconfigLayout.setVerticalGroup(
            pnlconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlconfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltituloconf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnewpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        rsnpanel.add(pnlconfig, "card4");

        pnlsoporte.setBackground(new java.awt.Color(255, 255, 255));
        pnlsoporte.setName("pnlsoporte"); // NOI18N

        lbltitulosoporte.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte.setText("Soporte Tecnico");
        lbltitulosoporte.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lbltitulosoporte.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WIFI_TETHERING);

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));

        lbltitulosoporte4.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte4.setText(" +593 99 757 3608");
        lbltitulosoporte4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbltitulosoporte4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);

        lbltitulosoporte2.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte2.setText(" Victor Romero");
        lbltitulosoporte2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbltitulosoporte2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulosoporte2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(lbltitulosoporte4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulosoporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulosoporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 153));

        lbltitulosoporte5.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte5.setText(" Wladimir Tocta");
        lbltitulosoporte5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbltitulosoporte5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);

        lbltitulosoporte6.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte6.setText(" +593 99 725 1924");
        lbltitulosoporte6.setToolTipText("");
        lbltitulosoporte6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbltitulosoporte6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulosoporte5, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(lbltitulosoporte6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulosoporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulosoporte6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));

        lbltitulosoporte3.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte3.setText(" Janer Torrales");
        lbltitulosoporte3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbltitulosoporte3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);

        lbltitulosoporte1.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulosoporte1.setText(" +593 99 330 3546");
        lbltitulosoporte1.setToolTipText("");
        lbltitulosoporte1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbltitulosoporte1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulosoporte3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(lbltitulosoporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulosoporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulosoporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlsoporteLayout = new javax.swing.GroupLayout(pnlsoporte);
        pnlsoporte.setLayout(pnlsoporteLayout);
        pnlsoporteLayout.setHorizontalGroup(
            pnlsoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsoporteLayout.createSequentialGroup()
                .addGroup(pnlsoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlsoporteLayout.createSequentialGroup()
                        .addContainerGap(117, Short.MAX_VALUE)
                        .addComponent(lbltitulosoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlsoporteLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pnlsoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        pnlsoporteLayout.setVerticalGroup(
            pnlsoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsoporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulosoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        rsnpanel.add(pnlsoporte, "card2");

        jPanel1.add(rsnpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 35, 670, 660));

        lblfecha.setForeground(new java.awt.Color(0, 0, 0));
        lblfecha.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        lblfecha.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        lblfecha.setName("lblfecha"); // NOI18N
        jPanel1.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 23));

        lblhora.setForeground(new java.awt.Color(0, 0, 0));
        lblhora.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        lblhora.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        lblhora.setName("lblhora"); // NOI18N
        jPanel1.add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 189, 24));

        rSLabelImage1.setBackground(new java.awt.Color(255, 255, 255));
        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 138));

        btnTurnos.setBackground(new java.awt.Color(0, 153, 0));
        btnTurnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/turno.png"))); // NOI18N
        btnTurnos.setText("Turnos");
        btnTurnos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnTurnos.setSelected(true);
        btnTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnConfig.setBackground(new java.awt.Color(0, 153, 0));
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/configuracion.png"))); // NOI18N
        btnConfig.setText("Configuracion");
        btnConfig.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        btnSoporte.setBackground(new java.awt.Color(0, 153, 0));
        btnSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/soporte.png"))); // NOI18N
        btnSoporte.setText("Soporte Tecnico");
        btnSoporte.setFont(new java.awt.Font("Comic Sans MS", 1, 17)); // NOI18N
        btnSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        rSButtonIconI6.setBackground(new java.awt.Color(0, 153, 0));
        rSButtonIconI6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cerrar.png"))); // NOI18N
        rSButtonIconI6.setText("Cerrar Sesion");
        rSButtonIconI6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        rSButtonIconI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconI6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Sistema Control de Turnos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(282, 282, 282))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        jLabel7.setBackground(new java.awt.Color(204, 255, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/17046-4k.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnosActionPerformed
        if (!this.btnTurnos.isSelected()) {
            this.btnTurnos.setSelected(true);
            this.btnSoporte.setSelected(false);
            this.btnConfig.setSelected(false);

            this.rsnpanel.setPanelSlider(2, this.pnlTurno, rojeru_san.RSPanelsSlider.DIRECT.RIGHT);

        }

    }//GEN-LAST:event_btnTurnosActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        if (!this.btnConfig.isSelected()) {
            this.btnTurnos.setSelected(false);
            this.btnSoporte.setSelected(false);
            this.btnConfig.setSelected(true);

            this.rsnpanel.setPanelSlider(2, pnlconfig, rojeru_san.RSPanelsSlider.DIRECT.RIGHT);
            id_login datos= new id_login();
            txtconfig_user.setText(datos.getUsuario());
        }

    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoporteActionPerformed
        if (!this.btnSoporte.isSelected()) {
            this.btnTurnos.setSelected(false);
            this.btnSoporte.setSelected(true);
            this.btnConfig.setSelected(false);

            this.rsnpanel.setPanelSlider(2, pnlsoporte, rojeru_san.RSPanelsSlider.DIRECT.RIGHT);
        }

    }//GEN-LAST:event_btnSoporteActionPerformed

    private void rSButtonIconI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI6ActionPerformed
        Login abrir = new Login();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonIconI6ActionPerformed

    private void rSButtonIconI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI1ActionPerformed
        
        
        JOptionPane.showMessageDialog(null, "contraseña actualizada correctamente");

    }//GEN-LAST:event_rSButtonIconI1ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        if (txtnewpass.getText().equals(txtnewpass2.getText())) {
            DBconnection conex = new DBconnection();
            boolean resultado = conex.actualizarclave(txtnewpass.getText());
            if (resultado == true) {
                JOptionPane.showMessageDialog(null, "contraseña actualizada correctamente");
                txtnewpass.setText("");
                txtnewpass2.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "error en actulizacion de contraseña");
            }
        } else {
            JOptionPane.showMessageDialog(null, "las contraseñas no coinciden");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void rSButtonIconI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI2ActionPerformed
        DBconnection conex = new DBconnection();
        boolean valor;
        try {
            valor = conex.turndiscapacidad(lblfecha.getText() +" "+ lblhora.getText());           
            if(valor==true)
            {
                txtnumeroturno.setText("T. S");
                txtcedula.setText("Turno Especial");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rSButtonIconI2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI btnConfig;
    private rojerusan.RSButtonIconI btnSoporte;
    private rojerusan.RSButtonIconI btnTurnos;
    private rojerusan.RSButtonIconI btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private RSMaterialComponent.RSLabelTextIcon lblfecha;
    private RSMaterialComponent.RSLabelTextIcon lblhora;
    private RSMaterialComponent.RSLabelTextIcon lbltituloconf;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte1;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte2;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte3;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte4;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte5;
    private RSMaterialComponent.RSLabelTextIcon lbltitulosoporte6;
    private javax.swing.JPanel pnlTurno;
    private javax.swing.JPanel pnlconfig;
    private javax.swing.JPanel pnlsoporte;
    private rojerusan.RSButtonIconI rSButtonIconI1;
    private rojerusan.RSButtonIconI rSButtonIconI2;
    private rojerusan.RSButtonIconI rSButtonIconI6;
    private rojerusan.RSLabelImage rSLabelImage1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private rojeru_san.RSPanelsSlider rsnpanel;
    private javax.swing.JLabel txtcedula;
    private javax.swing.JLabel txtconfig_user;
    private rojeru_san.RSMPassView txtnewpass;
    private rojeru_san.RSMPassView txtnewpass2;
    private javax.swing.JLabel txtnumeroturno;
    // End of variables declaration//GEN-END:variables

}
